volumes:
  database:
  database_config:

services:

  database:
    image: mariadb:10.9.3
    ports:
    - 3306:3306
    environment:
      # ! do not use this in production
      - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    volumes:
      - database:/var/lib/mysql
      - database_config:/etc/mysql

  phpmyadmin:
      image: phpmyadmin:latest
      restart: unless-stopped
      ports:
          - 8080:80
      environment:
          # we specify that we connect to an arbitrary server with the flag below
          # "arbitrary" means you're able to specify which database server to use on login page of phpmyadmin      
          - PMA_ARBITRARY=1